#!/usr/bin/env php
<?php

declare(strict_types=1);

include 'vendor/autoload.php';

use GarettRobson\PhpCommitLint\Application\LintApplication;

$application = new LintApplication();

$application->run();
