#!/usr/bin/env php
<?php

declare(strict_types=1);

include 'vendor/autoload.php';

use GarettRobson\PhpCommitLint\Application\PhpCommitLintApplication;

(new PhpCommitLintApplication())
    ->setDefaultCommand('lint', true)
    ->run()
;
